### ISSUE TITLE
All content related to "blockesp" will be misplaced.

### ISSUE THREAD

**Issue by Uoutai** [Zergatul/cheatutils#135]
Minecraft version: 1.21 
Java: zulu21 Mod 
version: cheatutils-3.3.2-fabric-1.21.jar 
Question:I have also encountered similar issues before. I used the RESCAN CHUNKS on the page, but it didn't seem to work.

![Image](https://github.com/user-attachments/assets/5cafe0be-e72c-4cd7-afdf-04952fa06169)

**Comment by Zergatul** [comment]
I remember something similar was happening to someone before. But I don't remember how we fixed it, or if we fixed it at all. Possibly some conflict with another mod.

**Comment by Uoutai** [comment]
Sorry for replying so late. When I raised the question, I updated a few mods but didn't add any new ones. Today, I updated a few more mods and rolled back to the previous version, but it still doesn't work.

![Image](https://github.com/user-attachments/assets/b224ace5-cb7b-4c34-9587-9a86110ea6dd)

**Comment by Zergatul** [comment]
I don't remember these mods. Can you determine exact mod causing the issue? If it is open source I can check why the problem happens

**Comment by Uoutai** [comment]
I'm not sure if it's caused by the mods either, because I updated these mods that day and when I started the game, the structure was misaligned. You don't need to check so many things, because some of them were updated today. I'll take new screenshots for you.

![Image](https://github.com/user-attachments/assets/1a7eb15d-aa60-49d1-8f60-8c9395ff3a47)

**Comment by Uoutai** [comment]
This is a startup log file. I'm not sure if it will be useful.

[latest.log](https://github.com/user-attachments/files/19645015/latest.log)

**Comment by Zergatul** [comment]
I don't see anything that can be related to this problem in the log.

**Comment by Uoutai** [comment]
Yes, I re-created an integration package with only fabric-api and cheatutils in it. Now cheatutils is working properly. Now I know for sure that there is a mod that is causing this problem.

**Comment by Uoutai** [comment]
emmm, it seems that it is not a mod problem, it may be a configuration problem in the minihud module, I send you a copy of the minihud config file

[minihud.json](https://github.com/user-attachments/files/19647219/minihud.json)

**Comment by Uoutai** [comment]
I know that is structural overlayStructureMainToggle inside this option As long as closed to normal

![Image](https://github.com/user-attachments/assets/3e548f2f-7741-4d98-9f2f-4a8b460a6ece)

**Comment by Zergatul** [comment]
> I know that is structural overlayStructureMainToggle inside this option As long as closed to normal

Sorry, I don't understand. You say this toggle is responsible for misplacements in cheatutils?

**Comment by Uoutai** [comment]
Yes, if you turn on this switch, the block ESP structure will be misaligned. You can try the minihud mod.

**Comment by Zergatul** [comment]
Ok, I will check why this happens

**Comment by Zergatul** [comment]
This is problem in MiniHUD code. I made a fix in their repository: https://github.com/maruohon/minihud/pull/389

**Comment by Zergatul** [comment]
The fix is in the current MiniHUD maintainer repo, but we don't know when the release with this fix will happen: https://github.com/sakura-ryoko/minihud/pull/129

**Comment by Zergatul** [comment]
You can download fixed MiniHUD versions for 1.21+ here: https://github.com/sakura-ryoko/minihud/releases
